### ISSUE TITLE
Finetuning on own data

### ISSUE THREAD

**Issue by ayylemao** [allenai/molmo#10]
Hello,
Thank you for publishing all this.
I would like to finetune Molmo-7B-D-0924 on my own data, specifically on pointing data. But i cannot seem to get your scripts to run, or find out how to supply the data to the model.
Do you have any resources to do this?
Is this possible with the HF trainer?

**Comment by chrisc36** [comment]
It might be possible with the HF trainer, but we don't provide code ourselves to train it that way.

If there is an issue with the scripts let us know what specificly is going wrong and we will work to try and fix it.

**Comment by ayylemao** [comment]
I am trying to get the scripts working. Firstly i downloaded the .tar with Molmo-7B-D-0924. 
Then i tried to run something like:
`torchrun launch_scripts/train_captioner.py config.yaml --nproc-per-node 2`
which immedialtly yields
```
Traceback (most recent call last):
  File "/home/jbxgpu01/projects/molmo-finetune/molmo/launch_scripts/train_captioner.py", line 9, in <module>
    from launch_scripts.utils import DEBUG_MODEL, VISION_BACKBONES, LLMS, DEFAULT_LOAD_PATHS
ModuleNotFoundError: No module named 'launch_scripts'`
```
Other than that, its not really clear how and where to supply and in what format the training data should be for new pointing data.

For our planned production purpose, we'd need to run Molmo with the vLLM backend for faster inference, do you know if a finetuned model with your scripts can be converted back to vLLM format?

**Comment by chrisc36** [comment]
I am not sure we have script for that here yet, but the models trained with this repo will be compatible with the Molmo in vLLM.

I think setting PYTHONPATH to your current directory: ``` PYTHONPATH=`pwd` ``` should fix that launch error.
