### ISSUE TITLE
pyproject.toml error

### ISSUE THREAD

**Issue by scm-aiml** [allenai/molmo#3]
The directions for install dependencies and the packages

```bash
git clone https://github.com/allenai/molmo.git
cd molmo
pip install -e .[all]
```

thrown an error for project setup. Reccomend adding the following to `pyproject.toml`:

```python
[tool.setuptools]
include-package-data = true
packages = ["olmo"]  # <<< This is what's missing
```

**Comment by chrisc36** [comment]
You are right, it was accidentally removed. Fixed.
