### ISSUE TITLE
we can't download the allenai/pixmo-clocks dataset from the url. can you give me the correct url formate to download the dataset!

### ISSUE THREAD

**Issue by dahwin** [allenai/molmo#4]
```python
from datasets import load_dataset
import requests
from PIL import Image
import io
import matplotlib.pyplot as plt

# Load the dataset
dataset_name = "allenai/pixmo-clocks"
train_split = load_dataset(dataset_name, split="train")

def get_watch_image(watchface_id, time_str):
    # Construct the Facer.io URL with more specific parameters
    base_url = f"https://facer.io/api/watchface/{watchface_id}/image"
    
    # Add headers to mimic a browser request
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'image/jpeg, image/png, image/webp',
        'Referer': 'https://facer.io/'
    }
    
    try:
        # Download the image with headers
        response = requests.get(base_url, headers=headers)
        if response.status_code == 200:
            # Print content type for debugging
            print(f"Content-Type: {response.headers.get('content-type', 'unknown')}")
            
            # Convert the response content to an image
            img = Image.open(io.BytesIO(response.content))
            
            # Display the image
            plt.figure(figsize=(10, 10))
            plt.imshow(img)
            plt.axis('off')
            plt.title(f"Watch Face ID: {watchface_id}\nTime: {time_str}")
            plt.show()
        else:
            print(f"Failed to download image: Status code {response.status_code}")
            print(f"Response content: {response.text[:200]}")  # Print first 200 chars of response
    except Exception as e:
        print(f"Error downloading/displaying image: {e}")
        print(f"Response status code: {response.status_code}")

# Example: Display the first watch face from the dataset
first_example = train_split[0]
get_watch_image(
    first_example['watchface_id'],
    first_example['watch_time']
)

```

Content-Type: text/html; charset=utf-8
Error downloading/displaying image: cannot identify image file <_io.BytesIO object at 0x7a44500b62f0>
Response status code: 200

**Comment by dahwin** [comment]
```
!python3 /content/molmo/scripts/download_data.py PixMoPoints --n_proc 12


```



/content/molmo/olmo/data/dataset.py:11: UserWarning: MOLMO_DATA_DIR is not set, data loading might fail
  warnings.warn("MOLMO_DATA_DIR is not set, data loading might fail")
2024-12-06 13:22:20.117	3549dabcafac:0	root:62	INFO	Starting download for PixMoPoints (1/1)
2024-12-06 13:22:20.117	3549dabcafac:0	olmo.util:174	CRITICAL	Uncaught TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/content/molmo/scripts/download_data.py", line 75, in <module>
    download()
  File "/content/molmo/scripts/download_data.py", line 70, in download
    raise e
  File "/content/molmo/scripts/download_data.py", line 64, in download
    dataset.download(n_procs=args.n_procs)
  File "/content/molmo/olmo/data/pixmo_datasets.py", line 160, in download
    local_names = [join(PIXMO_DATASETS, f"points-{name}") for name in collection_method]
  File "/content/molmo/olmo/data/pixmo_datasets.py", line 160, in <listcomp>
    local_names = [join(PIXMO_DATASETS, f"points-{name}") for name in collection_method]
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by chrisc36** [comment]
Downloading the clock images is a bit more complicated since the images are displayed in a canvas HTML element. To get them the easiest thing to do is to take a screenshot of the page. The page itself will be: `https://facer.io/watchface/{watchface_id}`

**Comment by ChaoliuW** [comment]
> Downloading the clock images is a bit more complicated since the images are displayed in a canvas HTML element. To get them the easiest thing to do is to take a screenshot of the page. The page itself will be: `https://facer.io/watchface/{watchface_id}`
Sorry to bother you, is there any other way to get the pictures?

**Comment by ChaoliuW** [comment]
> Downloading the clock images is a bit more complicated since the images are displayed in a canvas HTML element. To get them the easiest thing to do is to take a screenshot of the page. The page itself will be: `https://facer.io/watchface/{watchface_id}`

Downloading the clock images is a bit more complicated since the images are displayed in a canvas HTML element. To get them the easiest thing to do is to take a screenshot of the page. The page itself will be: https://facer.io/watchface/{watchface_id}
Sorry to bother you, is there any other way to get the pictures?

**Comment by ChaoliuW** [comment]
> Downloading the clock images is a bit more complicated since the images are displayed in a canvas HTML element. To get them the easiest thing to do is to take a screenshot of the page. The page itself will be: `https://facer.io/watchface/{watchface_id}`


Sorry to bother you, is there any other way to get the pictures?
