### ISSUE TITLE
There is an issue with downloading the dataset

### ISSUE THREAD

**Issue by GabrielGan1996** [allenai/molmo#7]
When downloading the Points dataset, the image download progress gets stuck, and the same issue occurs even after restarting. How can this be resolved?
<img width="563" alt="image" src="https://github.com/user-attachments/assets/c667ab09-f8ca-47dc-82b7-0fbcb04e0138">

**Comment by chrisc36** [comment]
Strange, I am not sure why that would occur. You could try running with a single process and seeing if it can finish in that case.

**Comment by yomin-y** [comment]
Has this problem been resolved? how to solve it

**Comment by yomin-y** [comment]
> When downloading the Points dataset, the image download progress gets stuck, and the same issue occurs even after restarting. How can this be resolved? <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/131234374/394077034-c667ab09-f8ca-47dc-82b7-0fbcb04e0138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNzA1MjIsIm5iZiI6MTczNTI3MDIyMiwicGF0aCI6Ii8xMzEyMzQzNzQvMzk0MDc3MDM0LWM2NjdhYjA5LWY4Y2EtNDdkYy04MmI3LTBmYmNiMDRlMDEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMzMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWUyYWE0YTNlYjEyNDM1YTQ5YzgwMTIwODU2NzlkNmMxNTI4MDRiM2QyOThmOGIzMDQ2ZGFlYTI1NGFmNmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VVrdi3k3CbW0AyV7xQPf3cfbSiPGwYjgyeeCG1djZ_A">

hello~,Has this problem been resolved? how to solve it

**Comment by GabrielGan1996** [comment]
@yomin-y I solved the problem by switching to a more stable network.

**Comment by yi-ming-qian** [comment]
I tried to download PixMoPoints with just one process: `python3 scripts/download_data.py PixMoPoints --n_proc 1`

Still the downloading process is stuck. Are there other alternative ways for data downloading? @chrisc36

**Comment by yi-ming-qian** [comment]
I think I found the reason causing the issue. For example, when I go to this url:https://celebrity-feet.com/wp-content/uploads/cdn5336/maggie-grace-feet-13-photos-007.jpg , the website says: "this site is currently under going scheduled maintenance...please check back soon..."

The code should be modified to better support this kind of issue.
